// Generated by gencpp from file ur10e_rg2_moveit/Ur10eTrajectory.msg
// DO NOT EDIT!


#ifndef UR10E_RG2_MOVEIT_MESSAGE_UR10ETRAJECTORY_H
#define UR10E_RG2_MOVEIT_MESSAGE_UR10ETRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <moveit_msgs/RobotTrajectory.h>

namespace ur10e_rg2_moveit
{
template <class ContainerAllocator>
struct Ur10eTrajectory_
{
  typedef Ur10eTrajectory_<ContainerAllocator> Type;

  Ur10eTrajectory_()
    : trajectory()  {
    }
  Ur10eTrajectory_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::moveit_msgs::RobotTrajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::moveit_msgs::RobotTrajectory_<ContainerAllocator> >> _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct Ur10eTrajectory_

typedef ::ur10e_rg2_moveit::Ur10eTrajectory_<std::allocator<void> > Ur10eTrajectory;

typedef boost::shared_ptr< ::ur10e_rg2_moveit::Ur10eTrajectory > Ur10eTrajectoryPtr;
typedef boost::shared_ptr< ::ur10e_rg2_moveit::Ur10eTrajectory const> Ur10eTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator1> & lhs, const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator1> & lhs, const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10e_rg2_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "054c09e62210d7faad2f9fffdad07b57";
  }

  static const char* value(const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x054c09e62210d7faULL;
  static const uint64_t static_value2 = 0xad2f9fffdad07b57ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10e_rg2_moveit/Ur10eTrajectory";
  }

  static const char* value(const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_msgs/RobotTrajectory[] trajectory\n"
"================================================================================\n"
"MSG: moveit_msgs/RobotTrajectory\n"
"trajectory_msgs/JointTrajectory joint_trajectory\n"
"trajectory_msgs/MultiDOFJointTrajectory multi_dof_joint_trajectory\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/MultiDOFJointTrajectory\n"
"# The header is used to specify the coordinate frame and the reference time for the trajectory durations\n"
"Header header\n"
"\n"
"# A representation of a multi-dof joint trajectory (each point is a transformation)\n"
"# Each point along the trajectory will include an array of positions/velocities/accelerations\n"
"# that has the same length as the array of joint names, and has the same order of joints as \n"
"# the joint names array.\n"
"\n"
"string[] joint_names\n"
"MultiDOFJointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/MultiDOFJointTrajectoryPoint\n"
"# Each multi-dof joint can specify a transform (up to 6 DOF)\n"
"geometry_msgs/Transform[] transforms\n"
"\n"
"# There can be a velocity specified for the origin of the joint \n"
"geometry_msgs/Twist[] velocities\n"
"\n"
"# There can be an acceleration specified for the origin of the joint \n"
"geometry_msgs/Twist[] accelerations\n"
"\n"
"duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
;
  }

  static const char* value(const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ur10eTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10e_rg2_moveit::Ur10eTrajectory_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "trajectory: ";
    if (v.trajectory.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::moveit_msgs::RobotTrajectory_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.trajectory[i]);
    }
    if (v.trajectory.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10E_RG2_MOVEIT_MESSAGE_UR10ETRAJECTORY_H
